apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: unidocs
data:
  FLASK_ENV: "production"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "app_db"
  DB_USER: "postgres"
  SECRET_KEY: "k8s-secret-key-change-in-production"
